flag_banners = {
    "Aceflux": "https://i.imgur.com/jizKnk2.png",
    "Agender": "https://i.imgur.com/ym3yMRW.png",
    "Alloace": "https://i.imgur.com/iUFFbN9.png",
    "Alloaro": "https://i.imgur.com/4EvO0EL.png",
    "Aroace": "https://i.imgur.com/YXDtZK0.png",
    "Aroflux": "https://i.imgur.com/OoDkoEF.png",
    "Arogender": "https://i.imgur.com/9qJvZzy.png",
    "Aromantic": "https://i.imgur.com/wscgBcT.png",
    "Asexual": "https://i.imgur.com/ae0uNED.png",
    "Bigender": "https://i.imgur.com/yH7564H.png",
    "Bigender alternative": "https://i.imgur.com/ButEsKe.png",
    "Bisexual": "https://i.imgur.com/RGfyjHo.png",
    "Cisgender": "https://i.imgur.com/bzPhASy.png",
    "Demiboy": "https://i.imgur.com/86wCULk.png",
    "Demigirl": "https://i.imgur.com/trGzdQX.png",
    "Demiromantic": "https://i.imgur.com/e727hCO.png",
    "Demisexual": "https://i.imgur.com/AJvHYfQ.png",
    "Gay man": "https://i.imgur.com/zFmQYGl.png",
    "Gay man 7-stripe": "https://i.imgur.com/ZjJgVwk.png",
    "Genderfluid": "https://i.imgur.com/NryHBlO.png",
    "Genderqueer": "https://i.imgur.com/3KYnULf.png",
    "Grey ace": "https://i.imgur.com/ZGlvyBS.png",
    "Grey aro": "https://i.imgur.com/yjEBLad.png",
    "Intersex": "https://i.imgur.com/zPdZzDv.png",
    "Lesbian": "https://i.imgur.com/RrIt9m7.png",
    "Loveless aro": "https://i.imgur.com/SrGlThE.png",
    "Nebularomantic": "https://i.imgur.com/CxaD0no.png",
    "Nonbinary": "https://i.imgur.com/cY0Faic.png",
    "Non-SAM aromantic": "https://i.imgur.com/3ytnwI6.png",
    "Non-SAM asexual": "https://i.imgur.com/eCO9o6R.png",
    "Omnisexual": "https://i.imgur.com/3ytnwI6.png",
    "Oriented Aroace": "https://i.imgur.com/QZ6cxvw.png",
    "Pansexual": "https://i.imgur.com/AbmKZI0.png",
    "Polyamorous": "https://i.imgur.com/L38921e.png",
    "Polysexual": "https://i.imgur.com/RoTZ5MI.png",
    "Pronoun Non-Conforming": "https://i.imgur.com/g7YwOvR.png",
    "Queer Chevron": "https://i.imgur.com/b3V6nWT.png",
    "Queer Stripes": "https://i.imgur.com/YB1e9xG.png",
    "Quoigender": "https://i.imgur.com/1pla7JD.png",
    "Quoiromantic": "https://i.imgur.com/tKqpRvu.png",
    "Quoisexual": "https://i.imgur.com/7mCpxMv.png",
    "Rainbow 6-stripe": "https://i.imgur.com/cmIisok.png",
    "Rainbow 8-stripe": "https://i.imgur.com/f3p9ehc.png",
    "Straight": "https://i.imgur.com/lfHe41q.png",
    "Straight alternative": "https://i.imgur.com/g03vECr.png",
    "Surgender": "https://i.imgur.com/X5vm20R.png",
    "Transfem": "https://i.imgur.com/RHw6AKV.png",
    "Transgender": "https://i.imgur.com/nULiq5L.png",
    "Transmasc": "https://i.imgur.com/rGj7cpd.png",
}
